# Header
nav:
  Home: /
  Archives: /archives
  About: /about
  Friends: /links
  # 追番: /bangumi
  # Categories: /category
  # Tags: /tag

# favicon
favicon: 

# logo
logo: 

# links
links:
  Github: https://github.com/Soulter
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: neutral

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# waline
waline:
  enable: false
  serverURL: 

# maple
maple:
  enable: false
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

